; OpenCog AtomSpace representation of TinyTransformer
; Compatible with URE, PLN, ECAN, and MOSES
; Generated by gguf-workbench

(use-modules (opencog))
(use-modules (opencog exec))
(use-modules (opencog ure))
(use-modules (opencog pln))

; === Core Atoms ===

(ConceptNode "TinyTransformer" (stv 1.0 1.0))

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "TinyTransformer")
  (ConceptNode "TransformerModel"))

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "TransformerModel")
  (ConceptNode "NeuralNetwork"))

(PredicateNode "hasVocabularySize")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasVocabularySize")
  (ListLink
    (ConceptNode "TinyTransformer")
    (ConceptNode "VocabSize10")))

(NumberNode "10")

(PredicateNode "hasEmbeddingDimension")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasEmbeddingDimension")
  (ListLink
    (ConceptNode "TinyTransformer")
    (ConceptNode "EmbedDim5")))

(NumberNode "5")

(PredicateNode "hasContextLength")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasContextLength")
  (ListLink
    (ConceptNode "TinyTransformer")
    (ConceptNode "ContextLen5")))

(PredicateNode "hasNumberOfBlocks")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasNumberOfBlocks")
  (ListLink
    (ConceptNode "TinyTransformer")
    (ConceptNode "Blocks1")))

(PredicateNode "hasAttentionHeads")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasAttentionHeads")
  (ListLink
    (ConceptNode "TinyTransformer")
    (ConceptNode "Heads1")))

(ConceptNode "EmbeddingLayer")

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "EmbeddingLayer")
  (ConceptNode "Layer"))

(MemberLink
  (ConceptNode "EmbeddingLayer")
  (ConceptNode "TinyTransformerLayers"))

(PredicateNode "hasInputDimension")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasInputDimension")
  (ListLink
    (ConceptNode "EmbeddingLayer")
    (ConceptNode "Dim10")))

(PredicateNode "hasOutputDimension")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasOutputDimension")
  (ListLink
    (ConceptNode "EmbeddingLayer")
    (ConceptNode "Dim5")))

(ConceptNode "SelfAttentionLayer")

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "SelfAttentionLayer")
  (ConceptNode "Layer"))

(MemberLink
  (ConceptNode "SelfAttentionLayer")
  (ConceptNode "TinyTransformerLayers"))

(PredicateNode "hasQueryProjection")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasQueryProjection")
  (ListLink
    (ConceptNode "SelfAttentionLayer")
    (ConceptNode "QueryWeights")))

(PredicateNode "hasKeyProjection")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasKeyProjection")
  (ListLink
    (ConceptNode "SelfAttentionLayer")
    (ConceptNode "KeyWeights")))

(PredicateNode "hasValueProjection")

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasValueProjection")
  (ListLink
    (ConceptNode "SelfAttentionLayer")
    (ConceptNode "ValueWeights")))

(ConceptNode "FeedForwardLayer")

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "FeedForwardLayer")
  (ConceptNode "Layer"))

(MemberLink
  (ConceptNode "FeedForwardLayer")
  (ConceptNode "TinyTransformerLayers"))

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasInputDimension")
  (ListLink
    (ConceptNode "FeedForwardLayer")
    (ConceptNode "Dim5")))

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasOutputDimension")
  (ListLink
    (ConceptNode "FeedForwardLayer")
    (ConceptNode "Dim5")))

(ConceptNode "OutputLayer")

(InheritanceLink (stv 1.0 1.0)
  (ConceptNode "OutputLayer")
  (ConceptNode "Layer"))

(MemberLink
  (ConceptNode "OutputLayer")
  (ConceptNode "TinyTransformerLayers"))

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasInputDimension")
  (ListLink
    (ConceptNode "OutputLayer")
    (ConceptNode "Dim5")))

(EvaluationLink (stv 1.0 1.0)
  (PredicateNode "hasOutputDimension")
  (ListLink
    (ConceptNode "OutputLayer")
    (ConceptNode "Dim10")))

(ConceptNode "InputTokens")

(ConceptNode "Embeddings")

(ConceptNode "AttentionOutput")

(ConceptNode "FFNOutput")

(ConceptNode "FinalOutput")

(ExecutionLink
  (SchemaNode "Embed")
  (ListLink
    (ConceptNode "InputTokens")
    (ConceptNode "Embeddings")))

(ExecutionLink
  (SchemaNode "SelfAttend")
  (ListLink
    (ConceptNode "Embeddings")
    (ConceptNode "AttentionOutput")))

(ExecutionLink
  (SchemaNode "FeedForward")
  (ListLink
    (ConceptNode "AttentionOutput")
    (ConceptNode "FFNOutput")))

(ExecutionLink
  (SchemaNode "Project")
  (ListLink
    (ConceptNode "FFNOutput")
    (ConceptNode "FinalOutput")))

; === Knowledge Base Rules ===


; Rule: If a model has embedding layer, it can process tokens
(ImplicationLink (stv 0.9 0.9)
  (MemberLink
    (ConceptNode "EmbeddingLayer")
    (ConceptNode "TinyTransformerLayers"))
  (EvaluationLink
    (PredicateNode "canProcessTokens")
    (ConceptNode "TinyTransformer")))


; Rule: If a model has attention, it can model dependencies
(ImplicationLink (stv 0.95 0.95)
  (MemberLink
    (ConceptNode "SelfAttentionLayer")
    (ConceptNode "TinyTransformerLayers"))
  (EvaluationLink
    (PredicateNode "canModelDependencies")
    (ConceptNode "TinyTransformer")))


; Rule: Sequential composition of layers
(BindLink
  (VariableList
    (VariableNode "$L1")
    (VariableNode "$L2")
    (VariableNode "$X")
    (VariableNode "$Y")
    (VariableNode "$Z"))
  (AndLink
    (ExecutionLink
      (VariableNode "$L1")
      (ListLink (VariableNode "$X") (VariableNode "$Y")))
    (ExecutionLink
      (VariableNode "$L2")
      (ListLink (VariableNode "$Y") (VariableNode "$Z"))))
  (ExecutionLink
    (SchemaNode "Compose")
    (ListLink
      (VariableNode "$L1")
      (VariableNode "$L2")
      (VariableNode "$X")
      (VariableNode "$Z"))))


; ECAN: Critical nodes get higher attention values
; Attention layer is most important
(SetLink
  (ConceptNode "SelfAttentionLayer" (av 100 10 1))
  (ConceptNode "EmbeddingLayer" (av 80 8 1))
  (ConceptNode "OutputLayer" (av 70 7 1)))


; MOSES: Define search space for hyperparameters
(DefineLink
  (DefinedSchemaNode "OptimizeTransformer")
  (LambdaLink
    (VariableList
      (TypedVariableLink (VariableNode "$embedding_dim") (TypeNode "NumberNode"))
      (TypedVariableLink (VariableNode "$num_heads") (TypeNode "NumberNode"))
      (TypedVariableLink (VariableNode "$num_blocks") (TypeNode "NumberNode")))
    (ExecutionOutputLink
      (GroundedSchemaNode "py:evaluate_transformer")
      (ListLink
        (VariableNode "$embedding_dim")
        (VariableNode "$num_heads")
        (VariableNode "$num_blocks")))))
